apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sre-technical-challenge.fullname" . }}
  labels:
    {{- include "sre-technical-challenge.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "sre-technical-challenge.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sre-technical-challenge.selectorLabels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["server"]
        ports:
        - name: http
          containerPort: {{ .Values.service.ports.api }}
          protocol: TCP
        env:
        {{- if .Values.env }}
        {{- tpl .Values.env . | nindent 10 }}
        {{- end }}
        {{- if .Values.livenessProbe }}
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 10 }}
        {{- end }}
        {{- if .Values.readinessProbe }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 10 }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}

