apiVersion: v1
kind: Service
metadata:
  name: {{ include "sre-technical-challenge.fullname" . }}
  labels:
    {{- include "sre-technical-challenge.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.http }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.ports.api }}
      targetPort: http
      protocol: TCP
      name: api
  selector:
    {{- include "sre-technical-challenge.selectorLabels" . | nindent 4 }}

